// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaKIRybj9Dm2tZYsJDSIKi0rKNjpnwkaA',
    appId: '1:836702428678:web:0744a0e5276096fd1bad87',
    messagingSenderId: '836702428678',
    projectId: 'sk-school-master',
    authDomain: 'sk-school-master.firebaseapp.com',
    storageBucket: 'sk-school-master.firebasestorage.app',
    measurementId: 'G-TTD0SG8PLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADFBhWXoGky6dBvppRGkd3_kimI8CNCLI',
    appId: '1:836702428678:android:cc3657204e1a1ff51bad87',
    messagingSenderId: '836702428678',
    projectId: 'sk-school-master',
    storageBucket: 'sk-school-master.firebasestorage.app',
  );
}
